#!/bin/bash
#
# start
# 	inicia Basher ejecutando socat como servidor.
#	Por defecto se escucha el puerto 80
#
# Autor: Gonzalo Gabriel Costa (twitter.com/gcosta87)
# Ver el archivo LICENSE para la informacion del liberación del codigo de este proyecto.
# web: https://github.com/gcosta87/basher


declare DEFAULT_PORT=80
declare DEFAULT_BINDIP="localhost"
declare PID_FILE=".pid"


if [[ $1 != '' ]]
then
	port=$1;
else
	port=$DEFAULT_PORT;
fi

bindIP=$DEFAULT_BINDIP;

echo "Inicializando Basher..."
socat TCP4-LISTEN:$port,bind="$bindIP",su=nobody,reuseaddr,fork EXEC:./server/basher.sh &
pid=$!;
echo $pid > "$PID_FILE";
echo "Proceso (id): $pid";
echo "Escuchando en $bindIP:$port"
echo