#!/bin/bash
#
# stop
# 	detiene el servicio Basher
#
# Autor: Gonzalo Gabriel Costa (twitter.com/gcosta87)
# Ver el archivo LICENSE para la informacion del liberación del codigo de este proyecto.
# web: https://github.com/gcosta87/basher
echo "deteniendo Basher..."
kill $(cat .pid);
rm .pid;
echo "El servicio ha sido detenido!."
echo